import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './Documentation.css';

const Documentation = () => {
  const navigate = useNavigate();

  const handleLogout = () => {
    // Add logout logic here (e.g., clear tokens, state, etc.)
    navigate('/login');
  };

  return (
    <div className="documentation-container">
      <header className="documentation-header">
        <div className="logo">AT-AT</div>
        <nav className="documentation-nav">
          <Link to="/home">Home</Link>
          <Link to="/dashboard">Dashboard</Link>
          <Link to="/public-templates">Public Templates</Link>
          <Link to="/settings">Settings</Link>
        </nav>
        <div className="user-info">
          <span>Welcome, User!</span>
          <button onClick={handleLogout} className="logout-btn">Logout</button>
        </div>
      </header>

      <main className="documentation-main">
        <section className="documentation-header-section">
          <h1>Documentation & Help Guides</h1>
          <Link to="/dashboard" className="back-btn">Back to Dashboard</Link>
        </section>

        <section className="guides-section">
          <h2>Getting Started</h2>
          <div className="guide-card">
            <h3>How to Set Up Your First Scan</h3>
            <p>Learn the steps to configure and run your first API security scan with AT-AT.</p>
            <Link to="/guide/1" className="guide-link">Read More</Link>
          </div>
          <div className="guide-card">
            <h3>Understanding Scan Results</h3>
            <p>Interpret security scores, alerts, and reports generated by AT-AT.</p>
            <Link to="/guide/2" className="guide-link">Read More</Link>
          </div>

          <h2>Advanced Features</h2>
          <div className="guide-card">
            <h3>Customizing Testing Profiles</h3>
            <p>Create and manage custom scan profiles tailored to your needs.</p>
            <Link to="/guide/3" className="guide-link">Read More</Link>
          </div>
          <div className="guide-card">
            <h3>Managing API Inventory</h3>
            <p>Add, edit, or remove APIs from your inventory for scanning.</p>
            <Link to="/guide/4" className="guide-link">Read More</Link>
          </div>

          <h2>Troubleshooting</h2>
          <div className="guide-card">
            <h3>Resolving Failed Scans</h3>
            <p>Steps to troubleshoot and fix issues with failed scan attempts.</p>
            <Link to="/guide/5" className="guide-link">Read More</Link>
          </div>
          <div className="guide-card">
            <h3>Contacting Support</h3>
            <p>Get help from our support team or community forums.</p>
            <Link to="/guide/6" className="guide-link">Read More</Link>
          </div>
        </section>
      </main>

      <footer className="documentation-footer">
        <p>© 2025 AT-AT (API Threat Assessment Tool) • COS301 Capstone Project. All rights reserved.</p>
        <div className="footer-links">
          <a href="#">Privacy Policy</a>
          <a href="#">Terms of Service</a>
        </div>
      </footer>
    </div>
  );
};

export default Documentation;