import React, { useContext } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { ThemeContext } from './App';
import { useAuth } from './AuthContext';
import './Documentation.css';

const Documentation = () => {
  const navigate = useNavigate();
  const { darkMode, toggleDarkMode } = useContext(ThemeContext);
  const { currentUser, logout, getUserFullName } = useAuth();
  const location = useLocation();

  const handleLogout = () => {
    const confirmLogout = window.confirm('Are you sure you want to logout?');
    if (confirmLogout) {
      logout();
      navigate('/login', { replace: true });
    }
  };

  // Loading state similar to other components
  if (!currentUser) {
    return (
      <div style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
        backgroundColor: darkMode ? '#1e1e1e' : '#f5f5f5',
        color: darkMode ? 'white' : '#333',
        fontFamily: 'Arial, sans-serif'
      }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{
            width: '50px',
            height: '50px',
            border: '3px solid #333',
            borderTop: '3px solid #6b46c1',
            borderRadius: '50%',
            animation: 'spin 1s linear infinite',
            margin: '0 auto 20px'
          }}></div>
          <p>Loading Documentation...</p>
          <style>{`
            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }
          `}</style>
        </div>
      </div>
    );
  }

  const userFullName = getUserFullName() || (currentUser.firstName ? `${currentUser.firstName} Doe` : 'User');

  return (
    <div className="documentation-container">
      <header className="documentation-header">
        <div className="logo">AT-AT</div>
        <nav className="documentation-nav">
          <Link to="/home" className={location.pathname === '/home' ? 'active' : ''}>Home</Link>
          <Link to="/dashboard" className={location.pathname === '/dashboard' ? 'active' : ''}>Dashboard</Link>
          <Link to="/public-templates" className={location.pathname === '/public-templates' ? 'active' : ''}>Public Templates</Link>
          <Link to="/settings" className={location.pathname === '/settings' ? 'active' : ''}>Settings</Link>
        </nav>
        <div className="user-info">
          <div className="user-profile">
            <span className="user-avatar">
              {currentUser.firstName?.charAt(0)?.toUpperCase() || 'U'}
            </span>
            <div className="user-details">
              <span className="user-greeting">Welcome back,</span>
              <span className="user-name">{userFullName}</span>
            </div>
          </div>
          <button onClick={handleLogout} className="logout-btn" title="Logout">
            Logout
          </button>
          <button onClick={toggleDarkMode} className="theme-toggle-btn" title="Toggle Theme">
            {darkMode ? '☀️' : '🌙'}
          </button>
        </div>
      </header>

      <main className="documentation-main">
        <section className="documentation-header-section">
          <h1>Documentation & Help Guides</h1>
          <Link to="/dashboard" className="back-btn">Back to Dashboard</Link>
        </section>

        <section className="guides-section">
          <h2>Getting Started</h2>
          <div className="guide-card">
            <h3>How to Set Up Your First Scan</h3>
            <p>Learn the steps to configure and run your first API security scan with AT-AT.</p>
            <Link to="/guide/1" className="guide-link">Read More</Link>
          </div>
          <div className="guide-card">
            <h3>Understanding Scan Results</h3>
            <p>Interpret security scores, alerts, and reports generated by AT-AT.</p>
            <Link to="/guide/2" className="guide-link">Read More</Link>
          </div>

          <h2>Advanced Features</h2>
          <div className="guide-card">
            <h3>Customizing Testing Profiles</h3>
            <p>Create and manage custom scan profiles tailored to your needs.</p>
            <Link to="/guide/3" className="guide-link">Read More</Link>
          </div>
          <div className="guide-card">
            <h3>Managing API Inventory</h3>
            <p>Add, edit, or remove APIs from your inventory for scanning.</p>
            <Link to="/guide/4" className="guide-link">Read More</Link>
          </div>

          <h2>Troubleshooting</h2>
          <div className="guide-card">
            <h3>Resolving Failed Scans</h3>
            <p>Steps to troubleshoot and fix issues with failed scan attempts.</p>
            <Link to="/guide/5" className="guide-link">Read More</Link>
          </div>
          <div className="guide-card">
            <h3>Contacting Support</h3>
            <p>Get help from our support team or community forums.</p>
            <Link to="/guide/6" className="guide-link">Read More</Link>
          </div>
        </section>
      </main>

      <footer className="documentation-footer">
        <p>© 2025 AT-AT (API Threat Assessment Tool) • COS301 Capstone Project. All rights reserved.</p>
        <div className="footer-links">
          <a href="#">Privacy Policy</a>
          <a href="#">Terms of Service</a>
          <a href="#">Help Center</a>
        </div>
      </footer>
    </div>
  );
};

export default Documentation;