import React from 'react';
import './Report.css';

const Report1 = () => {
    return (
        <div className="print-container">
            <header className="report-header">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4">
                    <div>
                        <h1 className="text-4xl font-bold text-indigo-600">AT-AT Scan Report</h1>
                        <p className="text-gray-600">API Threat Assessment Tool</p>
                    </div>
                    <div className="text-right mt-4 sm:mt-0">
                        <button onClick={() => window.print()} className="no-print btn btn-primary text-sm py-2 px-4 inline-flex items-center">
                            <svg className="h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                            </svg>
                            Print Report
                        </button>
                    </div>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                    <div>
                        <strong className="text-gray-700">API Assessed:</strong>
                        <p className="text-gray-600">My E-commerce Site API (api.mystore.com)</p>
                    </div>
                    <div>
                        <strong className="text-gray-700">Scan Date:</strong>
                        <p className="text-gray-600">May 15, 2025, 04:30 PM</p>
                    </div>
                    <div>
                        <strong className="text-gray-700">Testing Profile:</strong>
                        <p className="text-gray-600">OWASP Top 10 Quick Scan</p>
                    </div>
                </div>
                <div className="mt-6 text-center">
                    <p className="text-gray-700 text-lg">Overall Security Score:</p>
                    <p className="text-6xl font-bold text-red-600">A-</p>
                    <p className="text-sm text-gray-500">(Based on weighted severity of findings)</p>
                </div>
            </header>
            <section className="mb-8">
                <h2 className="section-title">Scan Summary</h2>
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-4">
                    <div className="metric-card">
                        <span className="metric-card-value text-red-600">2</span>
                        <span className="metric-card-label">Critical</span>
                    </div>
                    <div className="metric-card">
                        <span className="metric-card-value text-orange-500">5</span>
                        <span className="metric-card-label">High</span>
                    </div>
                    <div className="metric-card">
                        <span className="metric-card-value text-yellow-500">8</span>
                        <span className="metric-card-label">Medium</span>
                    </div>
                    <div className="metric-card">
                        <span className="metric-card-value text-blue-500">12</span>
                        <span className="metric-card-label">Low</span>
                    </div>
                    <div className="metric-card col-span-2 sm:col-span-1 lg:col-span-1">
                        <span className="metric-card-value text-gray-700">27</span>
                        <span className="metric-card-label">Total Findings</span>
                    </div>
                </div>
            </section>
            <section>
                <h2 className="section-title">Detailed Findings</h2>
                {/* Findings cards go here */}
            </section>
            <footer className="mt-12 pt-6 border-t border-gray-300 text-center text-sm text-gray-500">
                <p>This report was generated by AT-AT (API Threat Assessment Tool) on May 15, 2025.</p>
                <p>COS301 Capstone Project - [Your Team Name]</p>
                <p className="mt-2 no-print">
                    <a href="#" className="text-indigo-600 hover:underline">Back to Dashboard</a>
                </p>
            </footer>
        </div>
    );
};


export default Report1;

