name: Deploy_ATAT
on:
  workflow_run:
    workflows: ["Pipeline"]
    types:
      - completed
jobs:
  deploy-to-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Build and Push to Docker Hub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend 
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/atat-backend:latest 

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./api 
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/atat-api:latest 

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend 
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/atat-frontend:latest 

      - name: Deployment Initiated
        run: echo "Images pushed to Docker Hub. Ready for cloud deployment."